### ISSUE TITLE
docker file need updating

### ISSUE THREAD

**Issue by WeileiZeng** [tencent-quantum-lab/tensorcircuit#146]
## Issue Description

`tensorcircuit` is not installed in the image, as well as other issues after `pip install tensorcircuit`

## How to Reproduce

```shell
docker run -it --network host --gpus all tensorcircuit/tensorcircuit
root@user-HP-Z8-G4-Workstation:/app# python
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorcircuit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorcircuit'
>>>
```

**Comment by refraction-ray** [comment]
thanks for the report, tensorcircuit is indeed not installed in the docker, it can be used via pip or there is a latest version tensorcircuit source code in the docker which can be used or some local develop version of tensorcircuit codebase can be mounted to the docker. (maybe I better to record the expected behavior somewhere)

Could you kindly remind me what other issues are within the docker?

**Comment by WeileiZeng** [comment]
perhaps some module compatibility issue. you can see it after `pip install tensorcircuit`, otherwise none.
